Update sync_to_huggingface_hub.yml

diff --git a/.github/workflows/sync_to_huggingface_hub.yml b/.github/workflows/sync_to_huggingface_hub.yml
--- a/.github/workflows/sync_to_huggingface_hub.yml
+++ b/.github/workflows/sync_to_huggingface_hub.yml
@@ -17,6 +17,17 @@ jobs:
       - name: Create models folder
         run: mkdir -p movie-recommendation-system/models
 
+      - name: Fail if TMDB file is present
+        run: |
+          if [ -f data/*.csv ]; then
+            echo "TMDB file detected! Aborting push."
+            exit 1
+          fi
+
+      - name: Prepare files for Hugging Face push (exclude TMDB)
+        run: |
+            rsync -av --exclude='data/*.csv' . output_dir/
+
 
       - name: Download movies.pkl from Google Drive
         run: |
